/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/trackables` | `/trackables`; params?: Router.UnknownInputParams; } | { pathname: `/_components/DayCellRange`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dateController`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCell`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellBoolean`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellNumber`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellProvider`; params?: Router.UnknownInputParams; } | { pathname: `/_components/trackableProvider`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/button`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/spinner`; params?: Router.UnknownInputParams; } | { pathname: `/temp/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/trackables/[trackableId]` | `/trackables/[trackableId]`, params: Router.UnknownInputParams & { trackableId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/trackables` | `/trackables`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/DayCellRange`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/dateController`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/dayCell`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/dayCellBoolean`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/dayCellNumber`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/dayCellProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/_components/trackableProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/_ui/button`; params?: Router.UnknownOutputParams; } | { pathname: `/_ui/input`; params?: Router.UnknownOutputParams; } | { pathname: `/_ui/spinner`; params?: Router.UnknownOutputParams; } | { pathname: `/temp/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/trackables/[trackableId]` | `/trackables/[trackableId]`, params: Router.UnknownOutputParams & { trackableId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/trackables${`?${string}` | `#${string}` | ''}` | `/trackables${`?${string}` | `#${string}` | ''}` | `/_components/DayCellRange${`?${string}` | `#${string}` | ''}` | `/_components/dateController${`?${string}` | `#${string}` | ''}` | `/_components/dayCell${`?${string}` | `#${string}` | ''}` | `/_components/dayCellBoolean${`?${string}` | `#${string}` | ''}` | `/_components/dayCellNumber${`?${string}` | `#${string}` | ''}` | `/_components/dayCellProvider${`?${string}` | `#${string}` | ''}` | `/_components/trackableProvider${`?${string}` | `#${string}` | ''}` | `/_ui/button${`?${string}` | `#${string}` | ''}` | `/_ui/input${`?${string}` | `#${string}` | ''}` | `/_ui/spinner${`?${string}` | `#${string}` | ''}` | `/temp/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/trackables` | `/trackables`; params?: Router.UnknownInputParams; } | { pathname: `/_components/DayCellRange`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dateController`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCell`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellBoolean`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellNumber`; params?: Router.UnknownInputParams; } | { pathname: `/_components/dayCellProvider`; params?: Router.UnknownInputParams; } | { pathname: `/_components/trackableProvider`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/button`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/input`; params?: Router.UnknownInputParams; } | { pathname: `/_ui/spinner`; params?: Router.UnknownInputParams; } | { pathname: `/temp/create`; params?: Router.UnknownInputParams; } | `${'/(app)'}/trackables/${Router.SingleRoutePart<T>}` | `/trackables/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/trackables/[trackableId]` | `/trackables/[trackableId]`, params: Router.UnknownInputParams & { trackableId: string | number; } };
    }
  }
}
