version: "3"
services:
  node-next:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=1337
      - DATABASE_URL=postgresql://admin:samplepass@postgres:5432/db?connect_timeout=300
    command: "npm run dev:migrate"
    tty: true
  postgres:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=samplepass
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data
