version: "3"
services:
  node-next:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
volumes:
  pgdata:
