packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@date-fns/tz': 1.2.0
  '@rocicorp/zero': 0.20.2025052100
  '@tanstack/react-query': 5.80.7
  class-variance-authority: 0.7.1
  date-fns: 4.1.0
  prettier: 3.4.2
  tailwindcss: 4.1.17
  typescript: 5.7.3
  uuid: 11.0.5
  zod: 3.25.63

catalogs:
  react:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.0
    react: 19.1.0
    react-dom: 19.1.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
