packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.61.3
  "@trpc/client": 11.0.0-rc.645
  "@trpc/server": 11.0.0-rc.645
  "date-fns": "^3.6.0"
  "date-fns-tz": "^3.1.3"
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
