packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": 5.65.1
  "date-fns": 4.1.0
  "@date-fns/tz": 1.2.0
  "class-variance-authority": 0.7.1
  "@rocicorp/zero": 0.20.2025052100
  eslint: 9.17.0
  prettier: 3.4.2
  tailwindcss: 4.0.0
  typescript: 5.7.3
  uuid: 11.0.5
  zod: 3.25.63

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
