packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@date-fns/tz": 1.4.1
  "@rocicorp/zero": 0.24.3000000000
  "@tanstack/react-query": 5.90.8
  class-variance-authority: 0.7.1
  date-fns: 4.1.0
  dotenv-cli: 11.0.0
  prettier: 3.6.2
  tailwindcss: 4.1.17
  typescript: 5.9.3
  uuid: 13.0.0
  zod: 4.1.12

catalogs:
  react:
    "@types/react": ^19.2.4
    "@types/react-dom": ^19.2.3
    react: 19.2.0
    react-dom: 19.2.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
