packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": 5.63.0
  "date-fns": 4.1.0
  "@date-fns/tz": 1.2.0
  "class-variance-authority": 0.7.1
  eslint: 9.17.0
  prettier: 3.4.2
  tailwindcss: 3.4.17
  typescript: 5.7.3
  uuid: 11.0.4
  zod: 3.24.1

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.0
    "@types/react-dom": ^18.2.0
