packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/expo": 1.4.17
  "@date-fns/tz": 1.4.1
  "@tailwindcss/postcss": 4.1.18
  "@tailwindcss/vite": 4.1.18
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  better-auth: 1.4.17
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  date-fns: 4.1.0
  dotenv-cli: 11.0.0
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  jsdom: 27.4.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  typescript: 5.9.3
  uuid: 13.0.0
  vitest: 4.0.18
  zod: 4.3.6

catalogs:
  powersync:
    "@powersync/common": 1.46.0
    "@powersync/drizzle-driver": 0.7.2
    "@powersync/op-sqlite": 0.8.0
    "@powersync/react-native": 1.29.0
    "@powersync/react": 1.8.2
    "@powersync/web": 1.32.0
    "@op-engineering/op-sqlite": 15.2.5
    "@journeyapps/wa-sqlite": 1.4.1
  tanstack:
    "@tanstack/powersync-db-collection": 0.1.27
    "@tanstack/react-db": 0.1.67
    "@tanstack/react-form": 1.28.0
    "@tanstack/react-query": 5.90.20
    "@tanstack/react-router": 1.153.1
    "@tanstack/react-router-devtools": 1.153.1
    "@tanstack/react-router-ssr-query": 1.153.1
    "@tanstack/react-start": 1.153.1
    "@tanstack/react-store": 0.8.0
  react:
    "@types/react": ~19.1.10
    "@types/react-dom": 19.1.7
    react: 19.1.0
    react-dom: 19.1.0
    "babel-plugin-react-compiler": 1.0.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
