version: "3"
services:
  tyl-node-next:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - MIGRATE=true
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:samplepass@tyl-postgres:5432/db?connect_timeout=300
    tty: true
    depends_on:
      tyl-postgres:
        condition: service_healthy
  tyl-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=samplepass
      - POSTGRES_DB=db
    volumes:
      - tyl-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 20
      start_period: 5s

volumes:
  tyl-db:
