/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AuthPasswordresetImport } from './routes/auth/passwordreset'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotpasswordImport } from './routes/auth/forgotpassword'
import { Route as AppTestingImport } from './routes/app/testing'
import { Route as AppSettingsImport } from './routes/app/settings'
import { Route as AppCreateImport } from './routes/app/create'
import { Route as AppTrackablesIndexImport } from './routes/app/trackables/index'
import { Route as AppSettingsIndexImport } from './routes/app/settings/index'
import { Route as AppTrackablesIdImport } from './routes/app/trackables/$id'
import { Route as AppTrackablesIdIndexImport } from './routes/app/trackables/$id/index'
import { Route as AppTrackablesIdViewImport } from './routes/app/trackables/$id/view'
import { Route as AppTrackablesIdSettingsImport } from './routes/app/trackables/$id/settings'
import { Route as AppTrackablesIdImportImport } from './routes/app/trackables/$id/import'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthPasswordresetRoute = AuthPasswordresetImport.update({
  id: '/passwordreset',
  path: '/passwordreset',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotpasswordRoute = AuthForgotpasswordImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => AuthRoute,
} as any)

const AppTestingRoute = AppTestingImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppCreateRoute = AppCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)

const AppTrackablesIndexRoute = AppTrackablesIndexImport.update({
  id: '/trackables/',
  path: '/trackables/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsIndexRoute = AppSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)

const AppTrackablesIdRoute = AppTrackablesIdImport.update({
  id: '/trackables/$id',
  path: '/trackables/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppTrackablesIdIndexRoute = AppTrackablesIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrackablesIdRoute,
} as any)

const AppTrackablesIdViewRoute = AppTrackablesIdViewImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AppTrackablesIdRoute,
} as any)

const AppTrackablesIdSettingsRoute = AppTrackablesIdSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTrackablesIdRoute,
} as any)

const AppTrackablesIdImportRoute = AppTrackablesIdImportImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppTrackablesIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateImport
      parentRoute: typeof AppImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/app/testing': {
      id: '/app/testing'
      path: '/testing'
      fullPath: '/app/testing'
      preLoaderRoute: typeof AppTestingImport
      parentRoute: typeof AppImport
    }
    '/auth/forgotpassword': {
      id: '/auth/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/auth/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordImport
      parentRoute: typeof AuthImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/auth/passwordreset': {
      id: '/auth/passwordreset'
      path: '/passwordreset'
      fullPath: '/auth/passwordreset'
      preLoaderRoute: typeof AuthPasswordresetImport
      parentRoute: typeof AuthImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/trackables/$id': {
      id: '/app/trackables/$id'
      path: '/trackables/$id'
      fullPath: '/app/trackables/$id'
      preLoaderRoute: typeof AppTrackablesIdImport
      parentRoute: typeof AppImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexImport
      parentRoute: typeof AppSettingsImport
    }
    '/app/trackables/': {
      id: '/app/trackables/'
      path: '/trackables'
      fullPath: '/app/trackables'
      preLoaderRoute: typeof AppTrackablesIndexImport
      parentRoute: typeof AppImport
    }
    '/app/trackables/$id/import': {
      id: '/app/trackables/$id/import'
      path: '/import'
      fullPath: '/app/trackables/$id/import'
      preLoaderRoute: typeof AppTrackablesIdImportImport
      parentRoute: typeof AppTrackablesIdImport
    }
    '/app/trackables/$id/settings': {
      id: '/app/trackables/$id/settings'
      path: '/settings'
      fullPath: '/app/trackables/$id/settings'
      preLoaderRoute: typeof AppTrackablesIdSettingsImport
      parentRoute: typeof AppTrackablesIdImport
    }
    '/app/trackables/$id/view': {
      id: '/app/trackables/$id/view'
      path: '/view'
      fullPath: '/app/trackables/$id/view'
      preLoaderRoute: typeof AppTrackablesIdViewImport
      parentRoute: typeof AppTrackablesIdImport
    }
    '/app/trackables/$id/': {
      id: '/app/trackables/$id/'
      path: '/'
      fullPath: '/app/trackables/$id/'
      preLoaderRoute: typeof AppTrackablesIdIndexImport
      parentRoute: typeof AppTrackablesIdImport
    }
  }
}

// Create and export the route tree

interface AppSettingsRouteChildren {
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTrackablesIdRouteChildren {
  AppTrackablesIdImportRoute: typeof AppTrackablesIdImportRoute
  AppTrackablesIdSettingsRoute: typeof AppTrackablesIdSettingsRoute
  AppTrackablesIdViewRoute: typeof AppTrackablesIdViewRoute
  AppTrackablesIdIndexRoute: typeof AppTrackablesIdIndexRoute
}

const AppTrackablesIdRouteChildren: AppTrackablesIdRouteChildren = {
  AppTrackablesIdImportRoute: AppTrackablesIdImportRoute,
  AppTrackablesIdSettingsRoute: AppTrackablesIdSettingsRoute,
  AppTrackablesIdViewRoute: AppTrackablesIdViewRoute,
  AppTrackablesIdIndexRoute: AppTrackablesIdIndexRoute,
}

const AppTrackablesIdRouteWithChildren = AppTrackablesIdRoute._addFileChildren(
  AppTrackablesIdRouteChildren,
)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTestingRoute: typeof AppTestingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTrackablesIdRoute: typeof AppTrackablesIdRouteWithChildren
  AppTrackablesIndexRoute: typeof AppTrackablesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTestingRoute: AppTestingRoute,
  AppIndexRoute: AppIndexRoute,
  AppTrackablesIdRoute: AppTrackablesIdRouteWithChildren,
  AppTrackablesIndexRoute: AppTrackablesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordresetRoute: typeof AuthPasswordresetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordresetRoute: AuthPasswordresetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/testing': typeof AppTestingRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordreset': typeof AuthPasswordresetRoute
  '/app/': typeof AppIndexRoute
  '/app/trackables/$id': typeof AppTrackablesIdRouteWithChildren
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/trackables': typeof AppTrackablesIndexRoute
  '/app/trackables/$id/import': typeof AppTrackablesIdImportRoute
  '/app/trackables/$id/settings': typeof AppTrackablesIdSettingsRoute
  '/app/trackables/$id/view': typeof AppTrackablesIdViewRoute
  '/app/trackables/$id/': typeof AppTrackablesIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/testing': typeof AppTestingRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordreset': typeof AuthPasswordresetRoute
  '/app': typeof AppIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/trackables': typeof AppTrackablesIndexRoute
  '/app/trackables/$id/import': typeof AppTrackablesIdImportRoute
  '/app/trackables/$id/settings': typeof AppTrackablesIdSettingsRoute
  '/app/trackables/$id/view': typeof AppTrackablesIdViewRoute
  '/app/trackables/$id': typeof AppTrackablesIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/create': typeof AppCreateRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/testing': typeof AppTestingRoute
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passwordreset': typeof AuthPasswordresetRoute
  '/app/': typeof AppIndexRoute
  '/app/trackables/$id': typeof AppTrackablesIdRouteWithChildren
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/trackables/': typeof AppTrackablesIndexRoute
  '/app/trackables/$id/import': typeof AppTrackablesIdImportRoute
  '/app/trackables/$id/settings': typeof AppTrackablesIdSettingsRoute
  '/app/trackables/$id/view': typeof AppTrackablesIdViewRoute
  '/app/trackables/$id/': typeof AppTrackablesIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/create'
    | '/app/settings'
    | '/app/testing'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/passwordreset'
    | '/app/'
    | '/app/trackables/$id'
    | '/app/settings/'
    | '/app/trackables'
    | '/app/trackables/$id/import'
    | '/app/trackables/$id/settings'
    | '/app/trackables/$id/view'
    | '/app/trackables/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/create'
    | '/app/testing'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/passwordreset'
    | '/app'
    | '/app/settings'
    | '/app/trackables'
    | '/app/trackables/$id/import'
    | '/app/trackables/$id/settings'
    | '/app/trackables/$id/view'
    | '/app/trackables/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/create'
    | '/app/settings'
    | '/app/testing'
    | '/auth/forgotpassword'
    | '/auth/login'
    | '/auth/passwordreset'
    | '/app/'
    | '/app/trackables/$id'
    | '/app/settings/'
    | '/app/trackables/'
    | '/app/trackables/$id/import'
    | '/app/trackables/$id/settings'
    | '/app/trackables/$id/view'
    | '/app/trackables/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/create",
        "/app/settings",
        "/app/testing",
        "/app/",
        "/app/trackables/$id",
        "/app/trackables/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/forgotpassword",
        "/auth/login",
        "/auth/passwordreset"
      ]
    },
    "/app/create": {
      "filePath": "app/create.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings.tsx",
      "parent": "/app",
      "children": [
        "/app/settings/"
      ]
    },
    "/app/testing": {
      "filePath": "app/testing.tsx",
      "parent": "/app"
    },
    "/auth/forgotpassword": {
      "filePath": "auth/forgotpassword.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/passwordreset": {
      "filePath": "auth/passwordreset.tsx",
      "parent": "/auth"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/trackables/$id": {
      "filePath": "app/trackables/$id.tsx",
      "parent": "/app",
      "children": [
        "/app/trackables/$id/import",
        "/app/trackables/$id/settings",
        "/app/trackables/$id/view",
        "/app/trackables/$id/"
      ]
    },
    "/app/settings/": {
      "filePath": "app/settings/index.tsx",
      "parent": "/app/settings"
    },
    "/app/trackables/": {
      "filePath": "app/trackables/index.tsx",
      "parent": "/app"
    },
    "/app/trackables/$id/import": {
      "filePath": "app/trackables/$id/import.tsx",
      "parent": "/app/trackables/$id"
    },
    "/app/trackables/$id/settings": {
      "filePath": "app/trackables/$id/settings.tsx",
      "parent": "/app/trackables/$id"
    },
    "/app/trackables/$id/view": {
      "filePath": "app/trackables/$id/view.tsx",
      "parent": "/app/trackables/$id"
    },
    "/app/trackables/$id/": {
      "filePath": "app/trackables/$id/index.tsx",
      "parent": "/app/trackables/$id"
    }
  }
}
ROUTE_MANIFEST_END */
